In [3]:
people = {'hugh':49,'kate':35,'lucy':24,'bob':36}

In [4]:
#q2 
total = 0
for key in people:
     total += key

TypeError: unsupported operand type(s) for +=: 'int' and 'str'

In [7]:
# q2 
total = 0
for x in people.values():
     total += x

total

144

In [8]:
#q2
otal = sum(people.values())
total

144

In [11]:
#q2
total = 0
for key in people:
     total += people[key]

total

144

In [12]:
# Q3 
people['dan']

KeyError: 'dan'

In [14]:
#q4 
peoplelist = [{'name':'bob','age':28},{'name':'dylan','age':43},{'name':'cat','age':17}]
for item in peoplelist:
     if item['age']>30:
        print(item['name'])

dylan


In [18]:
# q5 

def mystery(x):
     if x > 0:
        return -x
     else:
        return x

In [21]:
mystery(0)

0

In [24]:
import numpy as np 

In [26]:
# q6 
c = np.array([[2,4,6,8],[12,14,16,18],[22,24,26,28]])
print(c)
[
[2,4,6,8]
[12,14,16,18]
[22,24,26,28]
]

[[ 2  4  6  8]
 [12 14 16 18]
 [22 24 26 28]]


<>:5: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:5: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
/var/folders/t6/r78__dnn0sjgvvll0tn49gn80000gn/T/ipykernel_41881/3814315128.py:5: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  [2,4,6,8]


TypeError: list indices must be integers or slices, not tuple

In [27]:
c.shape

(3, 4)

In [28]:
#Q7 
c[1,:]

array([12, 14, 16, 18])

In [29]:
# q8 
d = np.array([6,16,26])

In [30]:
d[d>10]=0

In [31]:
d

array([6, 0, 0])

In [33]:
from datetime import datetime

In [34]:
# q9 
D1 = datetime(2017,2,22,9,30)
D2 = datetime(2017,2,23,10,45)

In [35]:
D1<D2

True

In [36]:
D1-D2

datetime.timedelta(days=-2, seconds=81900)

In [42]:
# Q10 

In [46]:
# function to reyurn a list of those words whoes frequency is greater than a threshold provided

def top_words(word_freq, threshold):

    top = []

In [47]:
# reading the dict

for key in word_freq.keys():

    # checking if the frequenncy is greater than threshold

    if word_freq[key] > threshold:

        # if so the add key to list

        top.append(key)

NameError: name 'top' is not defined

In [48]:
# return the list so formed

return top



# test calls

word_freq = {'the':58, 'people':6, 'beautiful':8, 'cats':13, 'finally':9, 'this': 19, 'class': 21, 'is': 101, 'almost': 1, 'over':4}

print(top_words(word_freq, 10))

print(top_words(word_freq, 55))

print(top_words(word_freq, 100))

SyntaxError: 'return' outside function (1333253707.py, line 3)

In [149]:
# Q11 
import pandas as pd 
import numpy as np 

# read in data 
df = pd.read_csv('/Users/georgesmith/Downloads/eur.pop.rev.csv',skiprows=2)
df

Entity     01.01.89     01.01.90  \
0                                Austria    7602431.0    7660345.0   
1                                Belgium    9927600.0    9947800.0   
2                                Denmark    5129800.0    5135400.0   
3                                Finland    4954359.0    4974383.0   
4                                 France   56269800.0          NaN   
5                                Germany   61715000.0   62678000.0   
6                                Iceland     253500.0     255708.0   
7                                Ireland    3526600.0    3505500.0   
8                                  Italy   57504700.0   57576400.0   
9                              Luxemburg     374900.0     379300.0   
10                            Netherland   14805240.0   14892574.0   
11                                Norway    4226901.0    4241473.0   
12                              Portugal   10304700.0          NaN   
13                                 Spain   38851900.0   38924500.0   
14                                Sweden    8458890.0    8527040.0   
15                           Switzerland    6619973.0    6673850.0   
16                        United Kingdom   57236200.0   57410600.0   
17                                   NaN          NaN          NaN   
18                          Total Europe  325665440.0  326962674.0   
19                                   NaN          NaN          NaN   
20  Sources: Eurostat, national agencies          NaN          NaN   

       01.01.91     01.01.92     01.01.93     01.01.94     01.01.95  
0     7790957.0    7860800.0    7909575.0    7943652.0    8054800.0  
1     9987000.0   10068319.0   10100631.0   10130574.0   10143047.0  
2     5146500.0    5162100.0    5180614.0    5191000.0    5251027.0  
3     4998478.0    5029300.0    5054982.0    5098754.0    5116800.0  
4    56893000.0   57217500.0   57529577.0   57847000.0   58265400.0  
5    79753000.0   80238000.0   81338000.0   81353000.0   81845000.0  
6      259577.0     262193.0     264922.0     266783.0     267806.0  
7     3519000.0    3542000.0    3559985.0    3570700.0    3591200.0  
8    57746200.0   57788200.0   57114161.0   57201800.0   57268578.0  
9      384400.0     389800.0     395200.0     400000.0     412800.0  
10   15010445.0   15129200.0   15354000.0   15341553.0   15492800.0  
11    4261930.0    4273634.0    4324577.0    4348410.0    4370000.0  
12    9858500.0    9846000.0    9987500.0    9776000.0    9920800.0  
13   38993800.0   39055900.0   39790955.0   39177400.0   39241900.0  
14    8590630.0    8644100.0    8700000.0    8749000.0    8837000.0  
15    6750693.0    6831900.0    6871500.0    7021200.0    7060400.0  
16   57649200.0   58888800.0   58191230.0   58380000.0   58684000.0  
17          NaN          NaN          NaN          NaN          NaN  
18  345061045.0  347604719.0  348887853.0  348540020.0  372599752.0  
19          NaN          NaN          NaN          NaN          NaN  
20          NaN          NaN          NaN          NaN          NaN

In [150]:
# rename columns 
df=df.rename(columns = {' ':'Entity', '01.01.89':'1989', '01.01.90':'1990', '01.01.91':'1991', '01.01.92':'1992', '01.01.93':'1993', '01.01.94':'1994', '01.01.95':'1995' })

In [151]:

# fills Nas with 0 
df =df.fillna(0)
df.head()

Entity        1989       1990        1991        1992        1993  \
0  Austria   7602431.0  7660345.0   7790957.0   7860800.0   7909575.0   
1  Belgium   9927600.0  9947800.0   9987000.0  10068319.0  10100631.0   
2  Denmark   5129800.0  5135400.0   5146500.0   5162100.0   5180614.0   
3  Finland   4954359.0  4974383.0   4998478.0   5029300.0   5054982.0   
4   France  56269800.0        0.0  56893000.0  57217500.0  57529577.0   

         1994        1995  
0   7943652.0   8054800.0  
1  10130574.0  10143047.0  
2   5191000.0   5251027.0  
3   5098754.0   5116800.0  
4  57847000.0  58265400.0

In [154]:
# print each country that has more than 1,000,000 people in 1995 
print("\nCountry that has more than 1,000,000 people in 1995 : ");

for i in range(len(df)) :
    if df.loc[i,'1995'] >1000000:
        print(df.loc[i,"Entity"])


Country that has more than 1,000,000 people in 1995 : 
Austria
Belgium
Denmark
Finland
France
Germany
Ireland
Italy
Netherland
Norway
Portugal
Spain
Sweden
Switzerland
United Kingdom
Total Europe


In [157]:
# Avg population in the UK over those seven years 
df['Average Population']=df.iloc[:, [1,2,3,4,5,6,7]].mean(axis=1)
df.set_index("Entity", inplace = True)
average_value=df.loc['United Kingdom']['Average Population']
print("\nThe average population in the UK over those seven years : "+str(average_value))


The average population in the UK over those seven years : 58062861.428571425
