In [2]:
import numpy as np

In [5]:
array = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [6]:
array[2:4,2:4] 

array([[13, 14],
       [18, 19]])

In [7]:
d = []

for i in range(len(c[0,])):
    d.append(sum(c[0:4,i]))

d

[34, 38, 42, 46, 50]

In [8]:
# provided solution 
>>> nb4 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
>>> nb4
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])
>>> nb2 = nb4[2:,2:4]
>>> nb2
array([[13, 14],
       [18, 19]])
>>> nb4.sum()
210
>>> nb2.sum()
64
>>>

TypeError: 'numpy.ndarray' object is not callable