In [1]:
import numpy as np 

In [2]:
a = np.array ([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [6]:
a.dtype

dtype('int64')

In [7]:
a.shape

(3,)

In [9]:
b = np.array([[1,2,3],[4,5,6]])

In [10]:
type(b)

numpy.ndarray

In [11]:
b.shape

(2, 3)

In [13]:
a[0]

1

In [15]:
a[0] = 5

In [16]:
a

array([5, 2, 3])

In [17]:
b

array([[1, 2, 3],
       [4, 5, 6]])